name: Project Automation

on:
  issues:
    types: [opened, closed, reopened, assigned, unassigned, labeled, unlabeled]
  pull_request:
    types: [opened, closed, reopened, review_requested, review_request_removed]

jobs:
  update-project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to project board
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue || context.payload.pull_request;
            const projectNumber = 1; // プロジェクト番号を設定
            
            // 新規Issueは自動的にBacklogへ
            if (context.payload.action === 'opened') {
              console.log('New issue created, adding to backlog');
            }
            
            // ラベルに基づいてカラムを移動
            if (context.payload.action === 'labeled') {
              const label = context.payload.label.name;
              
              if (label === 'status: in-progress') {
                console.log('Moving to In Progress');
              } else if (label === 'status: ready-for-review') {
                console.log('Moving to Review');
              } else if (label === 'status: blocked') {
                console.log('Moving to Blocked');
              }
            }
            
            // Issue/PRがクローズされたらDoneへ
            if (context.payload.action === 'closed') {
              console.log('Moving to Done');
            }

  sync-to-management:
    runs-on: ubuntu-latest
    if: github.event.issue || github.event.pull_request
    steps:
      - name: Trigger management repo sync
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MANAGEMENT_REPO_TOKEN }}
          repository: sparkminan/vibey-tech-management
          event-type: project-update
          client-payload: '{"project": "claude-code-remote", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'